# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of existdb

name: Test and Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         exist-version: [latest, 6.0.1]
    services:
      # Label used to access the service container
      exist:
        image: existdb/existdb:${{ matrix.exist-version}}
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm start
      - run: npm test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
